### ISSUE TITLE
Does not work if the first character of query is non-ascii

### ISSUE THREAD

**Issue by ckf42** [psidex/CustomBangSearch#10]
When the first non-whitespace character after the bang is not an ascii word character, the bang is not matched

Examples:
* `!bang words` works
* `!bang Français` works
* `!bang çççççççç` does not work
* `!bang にほんご` does not work
* `!bang 👍` does not work
* `!bang emoji 👍` works
* `!bang #👍` does not work

 Seems that the issue comes from how `\b` treats non-ascii characters

**Comment by psidex** [comment]
Thanks, have fixed the broken regex and released v0.9.1
