### ISSUE TITLE
"Can't rename to bang currently in use" check is to aggressive.

### ISSUE THREAD

**Issue by Kl4rry** [psidex/CustomBangSearch#11]
If you want to add a bang which starts with a letter thats already taken you are not allowed to type that letter.

Example if i have
a = https://amazon.com/s?k=%s

and i try to add

abc = https://example.com?q=%s

Then i am not allowed to type the a in abc because a is already taken.

**Comment by psidex** [comment]
Yeah I see what you mean, good spot.

As a workaround for now you'll have to make the bang text box empty (e.g. add an unused letter such as z to the end of the bang, then delete the bang from the start) and you can then copy/paste your bang such as abc into it

**Comment by psidex** [comment]
So it turns out this is a problem that I think can only be fixed by changing the way in which the extension stores data internally.

I don't have a massive amount of time to work on this so this issue is probably going to exist for a while, unless someone else wants to have a go at fixing it!

**Comment by befocken** [comment]
Hey, I just proposed a MR to fix this issue. This also addresses the issue #16. If you got any comments, let me know :).
