### ISSUE TITLE
searX instances

### ISSUE THREAD

**Issue by Jorengarenar** [psidex/CustomBangSearch#34]
As of now, extension supports only two instances of searX ([searx.be](https://searx.be/), [searx.tiekoetter.com](https://searx.tiekoetter.com/)), but since one of the selling points of searX is having own instance of it, it would be nice to be have to either:

* automatic detection of searX regardless of domain
* glob patterns
* manually specified by user list of instances

**Comment by psidex** [comment]
So as far as I'm aware, [you always have to list out what hostnames you require or might require in the manifest file](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request), which means automatic detection regardless of domain isn't going to work.

Glob patterns could be an option, maybe something like `searx.*`? [I think that would be allowed](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns). The probelm with having a domain wildcard like that is that the extension is basically asking for permissions for all websites, which isn't very user friendly and is probably going to spook privacy concious people.

Manually specific list of instances is essentially what we have now.

**Comment by psidex** [comment]
I'm going to close this unless there's any more suggestions.
