### ISSUE TITLE
searX uses `!!` for external bangs

### ISSUE THREAD

**Issue by Jorengarenar** [psidex/CustomBangSearch#35]
As in the title, searX uses `!!` for bangs instead of `!`.  
Could the extension match it for the sake of consistency?
(preferably with the behaviour togglable)

**Comment by psidex** [comment]
Are you sure? The docs only mention a single ! - https://searx.github.io/searx/user/search_syntax.html

**Comment by Jorengarenar** [comment]
Docs of searX are slightly incomplete for some reason (but SearXNG has it [documented](https://docs.searxng.org/user/search-syntax.html#external-bangs)).

If we have a quick glance at [code in query.py](https://github.com/searx/searx/blob/75b859d2a897ceb3408c63390fc71034708f9f05/searx/query.py#L151) we can see `!!` for external bangs.  
Single `!` is for narrowing search engines in regular search.

**Comment by psidex** [comment]
Yep that checks out - I think it's definitely possible to add some sort of option to toggle support for treating `!!` the same as `!`.

If the option to use `!!` is enabled, would you want `!` to be disabled? Or use them bot at the same time?

**Comment by Jorengarenar** [comment]
I think it would be best to have `!` disabled then, for the sake of consistency

**Comment by psidex** [comment]
Hi @Jorengarenar, I've spent some time looking into this and I'm leaning towards not implementing this for now (and closing the issue). I think a nice feature for the future would be being able to customise what character(s) are considered a bang, but that would require a considerable rewrite of some core parts of the code. Apologies if you were expecing this to be implemented.

**Comment by Jorengarenar** [comment]
Well, that's unfortunate :(
