### ISSUE TITLE
[feature request] Inverting searX bang syntax

### ISSUE THREAD

**Issue by Jorengarenar** [psidex/CustomBangSearch#36]
In relation to issue #35, since authors of SearX(NG) don't really want to provide such ability, it would be really cool if this extension was capable of switching around behaviour of single `!` and double `!!`, i.e. it will convert `!gh` to `!!gh`.

**Comment by psidex** [comment]
Could you explain a little more what you mean by this? Maybe give an example?

CBS doesn't pass bangs to other services, it's all done in-extension. If you mean you want something that lets you use `!` as `!!` on searx, I feel like that's slightly outside of the scope of this extension.

**Comment by Jorengarenar** [comment]
>If you mean you want something that lets you use `!` as `!!` on searx

Yeah, that's precisely what I meant, but I can agree on it being outside of the scope here.
