### ISSUE TITLE
Allow for the Bangs list to be sorted

### ISSUE THREAD

**Issue by agsimmons** [psidex/CustomBangSearch#45]
Thanks for the extension :)

I believe sorting the list of Bangs would improve the user experience of adding/changing/deleting custom bangs.

Fully custom ordering may be overkill, but automatically sorting alphanumerically by bang name could work well.

**Comment by psidex** [comment]
Added with 21f5091, will release and push as v0.10.6 soon :)

**Comment by lslenders** [comment]
works perfectly! thanks!


Lieven

--

Lieven Slenders

MSc Geo-Information Science
+44 784 565 8580
lieven.slenders ***@***.***>@gmail.com



Op do 29 feb 2024 om 20:47 schreef Simon ***@***.***>:
