### ISSUE TITLE
Option to set empty bang redirect

### ISSUE THREAD

**Issue by cttps** [psidex/CustomBangSearch#49]
I don't know if this is intended, I'm assuming it is, but when you use a bang without a search query, it (seems to) default to just the URL itself, even if this isn't what might be intended by the user.

Ex: assigning `!c` to https://chatgpt.com/?temporary-chat=true redirects to https://chatgpt.com

**Comment by psidex** [comment]
Discussion is at #30 , please leave this comment there :)
